services:
  githubscan:
    image: cimg/python:3.10.4
    container_name: githubscan
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://githubdb/github"

    volumes:
      - .:/home/circleci/project/

    command: bash -c "pip install pip-tools pre-commit && pre-commit install && pip install -r requirements-dev.txt && python manage.py migrate && python manage.py runserver"

  githubdb:
    image: cimg/postgres:12.10
    container_name: githubdb

    environment:
      POSTGRES_USER: "circleci"
      POSTGRES_DB: "github"
