# -*- coding: utf-8 -*-
# Generated by Django 4.2.8 on 2024-01-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JsonStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanned_data", models.TextField()),
                ("uk_bank_holidays", models.TextField()),
                ("uk_bank_holidays_last_update", models.DateField()),
                ("processed_data", models.TextField()),
            ],
        ),
    ]
