# -*- coding: utf-8 -*-
# Generated by Django 4.2.8 on 2024-01-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_jsonstore_processed_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jsonstore",
            name="uk_bank_holidays_last_update",
            field=models.DateField(blank=True, null=True),
        ),
    ]
