# -*- coding: utf-8 -*-
# Generated by Django 4.2.8 on 2024-01-10 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_jsonstore_uk_bank_holidays_last_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jsonstore",
            name="uk_bank_holidays",
        ),
        migrations.RemoveField(
            model_name="jsonstore",
            name="uk_bank_holidays_last_update",
        ),
    ]
