# -*- coding: utf-8 -*-
# Generated by Django 4.2.8 on 2024-03-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_remove_jsonstore_uk_bank_holidays_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jsonstore",
            name="processed_data_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jsonstore",
            name="scanned_data_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
