# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-06-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "reporting_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Set True (checked / on) to enable reporting for this team.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamNotificationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Target email address for team-level notifications.",
                        max_length=254,
                    ),
                ),
                (
                    "red_alerts_only",
                    models.BooleanField(
                        default=False,
                        help_text="Set True (checked/on) to prevent green status notifications being sent.",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "email")},
            },
        ),
    ]
