# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationEmailTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Target email address for Organization Level Email",
                        max_length=254,
                    ),
                ),
                (
                    "reporting_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Set it to False (unchecked/off) to disable email notifications",
                    ),
                ),
            ],
        ),
    ]
