# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-06-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_organizationemailtarget"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrganizationEmailTarget",
            new_name="OrganizationNotificationTarget",
        ),
    ]
