# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "report",
            "0003_rename_organizationemailtarget_organizationnotificationtarget",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationnotificationtarget",
            name="id",
        ),
        migrations.AlterField(
            model_name="organizationnotificationtarget",
            name="email",
            field=models.EmailField(
                help_text="Target email address for Organization Level Email",
                max_length=254,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
