# -*- coding: utf-8 -*-
# Generated by Django 4.0.5 on 2022-08-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_enterpriseusers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EnterpriseUsers",
            new_name="EnterpriseUser",
        ),
    ]
