# -*- coding: utf-8 -*-
# Generated by Django 4.0.5 on 2022-08-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_rename_enterpriseusers_enterpriseuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAMLNotificationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=30)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Target email address obtail from SAML for team-level notifications.",
                        max_length=254,
                    ),
                ),
                (
                    "red_alerts_only",
                    models.BooleanField(
                        default=False,
                        help_text="Set True (checked/on) to prevent green status notifications being sent.",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "email")},
            },
        ),
    ]
