# -*- coding: utf-8 -*-
# Generated by Django 4.0.5 on 2022-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0007_samlnotificationtarget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterpriseuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="enterpriseuser",
            name="login",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
