# -*- coding: utf-8 -*-
# Generated by Django 4.0.5 on 2022-08-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_alter_enterpriseuser_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamnotificationtarget",
            name="login",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
