# -*- coding: utf-8 -*-
# Generated by Django 4.1.7 on 2023-10-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0010_remove_samlnotificationtarget_red_alerts_only_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="samlnotificationtarget",
            name="red_alerts_only",
            field=models.BooleanField(
                default=False,
                help_text="Set True (checked/on) to prevent green status notifications being sent.",
            ),
        ),
        migrations.AddField(
            model_name="teamnotificationtarget",
            name="red_alerts_only",
            field=models.BooleanField(
                default=False,
                help_text="Set True (checked/on) to prevent green status notifications being sent.",
            ),
        ),
    ]
