services:
  githubscan:
    image: python:3.11
    container_name: githubscan
    hostname: githubscan
    env_file:
      - .env
      - db.env
    environment:
      - DATABASE_URL=postgres://githubscan_db/githubscan
      - CELERY_BROKER_URL=redis://githubscan_rds:6379/0
      - CELERY_RESULT_BACKEND=redis://githubscan_rds:6379/0
      - CELERY_ALWAYS_EAGER = True
    dns:
      - 8.8.8.8
      - 4.4.4.4
    stdin_open: true
    tty: true
    links:
      - githubscan_db
      - githubscan_worker
      - githubscan_rds

    depends_on:
      - githubscan_db

  githubscan_db:
    image: postgres:14.8
    container_name: githubscan_db
    hostname: githubscan_db
    env_file:
      - db.env
    ports:
      - 5432:5432

  githubscan_worker:
    image: celery:4.0
    container_name: githubscan_worker
    hostname: githubscan_worker
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://githubscan_db/githubscan
      - CELERY_BROKER_URL=redis://githubscan_rds:6379/0
      - CELERY_RESULT_BACKEND=redis://githubscan_rds:6379/0
      - CELERY_ALWAYS_EAGER = True
    links:
      - githubscan_db
      - githubscan_rds

  githubscan_rds:
    image: redis:6.0
    container_name: githubscan_rds
    hostname: githubscan_rds
    ports:
      - 6379:6379
