query($org_name: String!,$first: Int!,$after: String){
  organization(login: $org_name){
    repositories(first: $first,after: $after )
    {
      pageInfo { 
        endCursor
        hasNextPage
      }
      edges {
        node {
            id
            name
          	url
            isArchived
        }
      }
    }
  }
}