query($org_name: String!,$repo_name:String!,$first: Int!,$after: String){
  organization(login: $org_name){
    repository(name: $repo_name ) {
      repositoryTopics (first:$first,after:$after) {
        	pageInfo {
          	hasNextPage
          	endCursor
        	}
        edges {
          node {
            topic{
              name
            }
          }
        }
       
      }
    }
  }
}