# Generated by Django 3.1.7 on 2021-03-10 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('name', models.CharField(max_length=100,
                                          primary_key=True, serialize=False)),
                ('skip_scan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100,
                                          primary_key=True, serialize=False)),
                ('repositories', models.ManyToManyField(to='github.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryVulnerabilityCount',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('critical', models.IntegerField()),
                ('high', models.IntegerField()),
                ('moderate', models.IntegerField()),
                ('low', models.IntegerField()),
                ('repository', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='github.repository')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryVulnerability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=50)),
                ('severity_level', models.CharField(max_length=20)),
                ('identifier_type', models.CharField(max_length=20)),
                ('identifier_value', models.CharField(max_length=20)),
                ('advisory_url', models.CharField(max_length=200, null=True)),
                ('published_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('publish_age_in_days', models.IntegerField(default=0)),
                ('detection_age_in_days', models.IntegerField(default=0)),
                ('slo_breach', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='github.repository')),
            ],
        ),
        migrations.CreateModel(
            name='RepositorySLOBreachCount',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('critical', models.IntegerField()),
                ('high', models.IntegerField()),
                ('moderate', models.IntegerField()),
                ('low', models.IntegerField()),
                ('repository', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='github.repository')),
            ],
        ),
    ]
