# Generated by Django 2.1.7 on 2019-04-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubTeam',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubTeamRepo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=100)),
                ('repository', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubVulnerabilityAlters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repository', models.CharField(max_length=100)),
                ('critical', models.IntegerField()),
                ('high', models.IntegerField()),
                ('moderate', models.IntegerField()),
                ('low', models.IntegerField()),
            ],
        ),
    ]
