# Generated by Django 2.1.7 on 2019-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('skip_scan', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GitHubTeam',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubTeamRepo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=100)),
                ('repository', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubVulnerabilityAlters',
            fields=[
                ('repository', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('critical', models.IntegerField()),
                ('high', models.IntegerField()),
                ('moderate', models.IntegerField()),
                ('low', models.IntegerField()),
            ],
        ),
    ]
