# Generated by Django 2.2.6 on 2019-10-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubTeamAdminEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=100)),
            ],
        ),
    ]
