# Generated by Django 2.1.7 on 2019-11-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitHubTeamAdminEmail',
        ),
        migrations.AddField(
            model_name='githubteam',
            name='admin_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
