# Generated by Django 3.2.3 on 2021-06-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_teamvulnerabilitycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryvulnerability',
            name='effective_severity_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='repositoryslobreachcount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repositoryvulnerabilitycount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamvulnerabilitycount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
