# Generated by Django 3.2.3 on 2021-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_auto_20210602_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryvulnerabilitycount',
            name='effective_critical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositoryvulnerabilitycount',
            name='effective_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositoryvulnerabilitycount',
            name='effective_slabreach',
            field=models.IntegerField(default=0),
        ),
    ]
