# Generated by Django 3.2.3 on 2021-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_auto_20210602_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamvulnerabilitycount',
            name='effective_critical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamvulnerabilitycount',
            name='effective_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamvulnerabilitycount',
            name='effective_slabreach',
            field=models.IntegerField(default=0),
        ),
    ]
