# Generated by Django 3.2.3 on 2021-06-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_auto_20210603_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryvulnerabilitycount',
            name='effective_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositoryvulnerabilitycount',
            name='effective_moderate',
            field=models.IntegerField(default=0),
        ),
    ]
