# Generated by Django 3.2.9 on 2022-01-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_organisationnotificationtarget_teamnotificationtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='enable_reporting',
            field=models.BooleanField(default=True, help_text='Set True (checked / on) to enable reporting for this team.'),
        ),
        migrations.AlterField(
            model_name='teamnotificationtarget',
            name='red_alerts_only',
            field=models.BooleanField(default=False, help_text='Set True (checked/on) to prevent green status notifications being sent.'),
        ),
    ]
