# Generated by Django 3.2.3 on 2021-06-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_auto_20210604_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamvulnerabilitycount',
            name='effective_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamvulnerabilitycount',
            name='effective_moderate',
            field=models.IntegerField(default=0),
        ),
    ]
