# Generated by Django 3.2.9 on 2022-01-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_auto_20220111_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='enable_reporting',
            new_name='reporting_enabled',
        ),
    ]
